AbeTime/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("Manager/", include("Manager.urls")),
    path("", include("User.urls")),
    path('sw.js', (TemplateView.as_view(template_name="User/sw.js",
    content_type='application/javascript', )), name='sw.js'),
]

Manager/urls.py
from django.urls import path
from Manager import views

app_name = 'Manager'
urlpatterns = [
    path("", views.ManagerIndexView.as_view(), name="index"),
    path("date/<year>/<month>/<day>", views.ManagerDateView.as_view(), name='date'),
    path("locations/", views.LocationsManageView.as_view(), name="locations_manage"),
    path("location_delete/<int:pk>", views.LocationDeleteView.as_view(), name="location_delete"),
    path("signup/", views.AbeSignUpView.as_view(), name="signup"),
    path("delete/", views.AbeUserDeleteView.as_view(), name="delete"),
]

User/urls.py
from django.urls import path
from User import views

app_name = 'User'
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("date/<int:year>/<int:month>/<int:day>", views.DateView.as_view(), name="date"),
    path("dateselect", views.DateSelectView.as_view(), name="date-select"),
    path("login/", views.AbeLoginView.as_view(), name="login"),
    path("logout/", views.AbeLogoutView.as_view(), name="logout")
]

Manager/models.py
from django.db import models

class WellKnownLocation(models.Model):
    location_name = models.CharField(max_length=300, unique=True)
    deletibility = models.BooleanField(default=True)

Manager/forms.py
from typing import Any, Mapping, Optional, Type, Union
from django import forms
from django.forms.utils import ErrorList
from User.models import AbeUser
from django.contrib.auth.forms import UserCreationForm

class LocationAddForm(forms.Form):
    location_name = forms.CharField(widget=forms.widgets.TextInput(attrs={'class': 'form-control'}))
        
class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #htmlの表示を変更可能にします
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['username'].label = 'ユーザー名'
        self.fields['username'].help_text = ''
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].label = 'パスワード'
        self.fields['password1'].help_text = ''
        self.fields['password2'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].label = 'パスワード(確認)'
        self.fields['password2'].help_text = '上のパスワードと同じものを入力してください'

    class Meta:
       model = AbeUser
       fields = ("username", "password1", "password2",)

class DeleteUserSelectForm(forms.Form):
    users = forms.ChoiceField(widget=forms.widgets.Select(attrs={'class': 'form-control'}), label='削除するユーザー')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['users'].choices = [(x.pk, x.username) for x in AbeUser.objects.filter(is_staff=False)]

Manager/views.py
from typing import Any, Dict
from django import http
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import (
    FormView,
    ListView,
    DeleteView,
    UpdateView,
    CreateView,
    TemplateView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django import forms

from .models import WellKnownLocation
from User.models import Log, AbeUser
from .forms import SignupForm, DeleteUserSelectForm, LocationAddForm

import datetime
from dateutil.relativedelta import relativedelta

# Create your views here.


class ManagerIndexView(LoginRequiredMixin, TemplateView):
    template_name = "Manager/index.html"

    def get(self, request, *args, **kwargs):
        if not self.request.user.is_staff:
            return redirect(reverse_lazy("User:index"))

        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        users = AbeUser.objects.filter(is_staff=False).order_by("id")
        ctx["users"] = users

        date_start: datetime.date
        date_end: datetime.date
        today = datetime.date.today()
        if today.day > 25:
            date_start = datetime.datetime.strptime(
                f"{today.year}-{today.month}-26", "%Y-%m-%d"
            ).date()
            date_end = date_start + relativedelta(months=1) - datetime.timedelta(days=1)
        else:
            date_end = datetime.datetime.strptime(
                f"{today.year}-{today.month}-25", "%Y-%m-%d"
            ).date()
            date_start = date_end - relativedelta(months=1) + datetime.timedelta(days=1)
        ctx["date_start"] = date_start
        ctx["date_end"] = date_end
        ctx["pre_date_start"] = date_start - relativedelta(months=1)

        counts = []
        map_time = [1, 0.5, 0]
        for user in users:
            counts.append(
                sum(
                    [
                        map_time[x.state]
                        for x in Log.objects.filter(
                            user=user, date__range=[date_start, date_end]
                        )
                    ]
                )
            )
        ctx["counts"] = counts

        state_choices = [(0, "◯"), ("1", "△"), ("2", "✕"), ("3", "---")]
        location_choices = [(location.id, location.location_name) for location in WellKnownLocation.objects.all().order_by('deletibility')]
        date_logs = []
        week_day_jp = ['月','火','水','木','金','土','日']
        for i in range((date_end - date_start).days + 1):
            logs = []
            for user in users:
                log = Log.objects.filter(user=user, date=date_start).first()
                form = forms.Form()
                if log == None:
                    form.fields[
                        "state_" + user.username + "_" + str(date_start)
                    ] = forms.ChoiceField(
                        widget=forms.widgets.Select(
                            attrs={"class": "form-control", "style": "font-size: 0.8em"}
                        ),
                        label="",
                        choices=state_choices,
                        initial=3,
                    )
                    form.fields[
                        "well_known_location_" + user.username + "_" + str(date_start)
                    ] = forms.ChoiceField(
                        widget=forms.widgets.Select(
                            attrs={"class": "form-control", "style": "font-size: 0.8em"}
                        ),
                        label="",
                        choices=location_choices,
                        initial=0,
                    )
                    form.fields[
                        "location_" + user.username + "_" + str(date_start)
                    ] = forms.CharField(
                        widget=forms.widgets.TextInput(
                            attrs={"class": "form-control", "style": "font-size: 0.8em"}
                        ),
                        label="",
                        required=False,
                    )
                    logs.append(form)
                else:
                    form.fields[
                        "state_" + user.username + "_" + str(date_start)
                    ] = forms.ChoiceField(
                        widget=forms.widgets.Select(
                            attrs={"class": "form-control", "style": "font-size: 0.8em"}
                        ),
                        label="",
                        choices=state_choices,
                        initial=log.state,
                    )
                    form.fields[
                        "well_known_location_" + user.username + "_" + str(date_start)
                    ] = forms.ChoiceField(
                        widget=forms.widgets.Select(
                            attrs={"class": "form-control", "style": "font-size: 0.8em"}
                        ),
                        label="",
                        choices=location_choices,
                        initial=log.well_known_location,
                    )
                    form.fields[
                        "location_" + user.username + "_" + str(date_start)
                    ] = forms.CharField(
                        widget=forms.widgets.TextInput(
                            attrs={"class": "form-control", "style": "font-size: 0.8em"}
                        ),
                        label="",
                        required=False,
                        initial=log.location,
                    )
                    logs.append(form)
            date_logs.append(((date_start,week_day_jp[date_start.weekday()]), logs))
            date_start = date_start + datetime.timedelta(days=1)
        ctx["date_logs"] = date_logs

        return ctx

    def post(self, request, *args, **kwargs):
        date_start: datetime.date
        date_end: datetime.date
        today = datetime.date.today()
        if today.day > 25:
            date_start = datetime.datetime.strptime(
                f"{today.year}-{today.month}-26", "%Y-%m-%d"
            ).date()
            date_end = date_start + relativedelta(months=1) - datetime.timedelta(days=1)
        else:
            date_end = datetime.datetime.strptime(
                f"{today.year}-{today.month}-25", "%Y-%m-%d"
            ).date()
            date_start = date_end - relativedelta(months=1) + datetime.timedelta(days=1)

        for i in range((date_end - date_start).days + 1):
            for user in AbeUser.objects.filter(is_staff=False).order_by("id"):
                state = int(
                    request.POST.get("state_" + user.username + "_" + str(date_start))
                )
                well_known_location = int(
                    request.POST.get("well_known_location_" + user.username + "_" + str(date_start))
                )
                location = request.POST.get(
                    "location_" + user.username + "_" + str(date_start)
                )
                if state != 3:
                    Log.objects.update_or_create(
                        user=user,
                        date=date_start,
                        defaults={"state": state, "well_known_location": well_known_location, "location": location},
                    )
            date_start = date_start + datetime.timedelta(days=1)

        return redirect(reverse_lazy("Manager:index"))


class ManagerDateView(LoginRequiredMixin, TemplateView):
    template_name = "Manager/date.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        users = AbeUser.objects.filter(is_staff=False).order_by("id")
        ctx["users"] = users

        date_start = datetime.datetime.strptime(
            str(self.kwargs.get("year"))
            + "-"
            + str(self.kwargs.get("month"))
            + "-"
            + str(self.kwargs.get("day")),
            "%Y-%m-%d",
        ).date()
        date_end = date_start + relativedelta(months=1) - datetime.timedelta(days=1)
        ctx["date_start"] = date_start
        ctx["date_end"] = date_end
        ctx["pre_date_start"] = date_start - relativedelta(months=1)
        ctx["next_date_start"] = date_start + relativedelta(months=1)
        if date_end < timezone.now().today().date():
            ctx["is_safe_date"] = True

        counts = []
        map_time = [1, 0.5, 0]
        for user in users:
            counts.append(
                sum(
                    [
                        map_time[x.state]
                        for x in Log.objects.filter(
                            user=user, date__range=[date_start, date_end]
                        )
                    ]
                )
            )
        ctx["counts"] = counts

        state_choices = [(0, "◯"), ("1", "△"), ("2", "✕"), ("3", "---")]
        location_choices = [(location.pk, location.location_name) for location in WellKnownLocation.objects.all().order_by('deletibility')]
        week_day_jp = ['月','火','水','木','金','土','日']
        date_logs = []
        for i in range((date_end - date_start).days + 1):
            logs = []
            for user in users:
                log = Log.objects.filter(user=user, date=date_start).first()
                form = forms.Form()
                if log == None:
                    form.fields[
                        "state_" + user.username + "_" + str(date_start)
                    ] = forms.ChoiceField(
                        widget=forms.widgets.Select(
                            attrs={"class": "form-control", "style": "font-size: 0.8em"}
                        ),
                        label="",
                        choices=state_choices,
                        initial=3,
                    )

Manager/templates/Manager/base.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'Manager:index' %}">安部板金</a>
        <div class="navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'Manager:locations_manage' %}">現場管理</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'Manager:signup' %}">ユーザー作成</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'Manager:delete' %}">ユーザー削除</a>
            </li>
          </ul>
        </div>
    
        <a class="navbar-text" href="{% url 'User:logout' %}">ログアウト</a>
      </div>
    </nav>
    {% block content %} {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

Manager/templates/Manager/date.html
{% extends 'Manager/base.html' %} {% block content %}
<form method="post" class="table-responsive d-flex flex-column mt-2">
  {% csrf_token %}
  <input type="submit" class="btn btn-primary w-75 my-3 mx-auto" value="更新" />
  <table class="table table-sm text-nowrap align-middle">
    <thead>
      <tr>
        <th class="col-2">
          <a href="{% url 'Manager:date' pre_date_start.year pre_date_start.month pre_date_start.day %}"><i class="bi bi-arrow-left-short"></i></a>{{ date_start.year }}/{{ date_start.month }}/{{ date_start.day }}~{{date_end.year }}/{{ date_end.month }}/{{ date_end.day }}
          {% if is_safe_date %}
          <a href="{% url 'Manager:date' next_date_start.year next_date_start.month next_date_start.day %}"><i class="bi bi-arrow-right-short"></i></a>
          {% endif %}
        </th>
        {% for user in users %}
        <th>{{ user.username }}</th>
        {% endfor %}
      </tr>
    </thead>
    {% for date, logs in date_logs %}
    {% if forloop.counter|divisibleby:'10' %}
    <tr>
      <th>
        {{ date_start.year }}/{{ date_start.month }}/{{ date_start.day }}~{{date_end.year }}/{{ date_end.month }}/{{ date_end.day }}
      </th>
      {% for user in users %}
      <th>{{ user.username }}</th>
      {% endfor %}
    </tr>
    {% endif %}
    <tr>
      <td>{{ date.0.year }}/{{ date.0.month }}/{{ date.0.day }}({{date.1}})</td>
      {% for log in logs %}
      <td>
        {% for field in log %}
        <p class="my-1">{{ field }}</p>
        {% endfor %}
      </td>
      {% endfor %}
    </tr>
    {% endfor %}
    <td>合計</td>
    {% for count in counts %}
    <td>{{count}}</td>
    {% endfor %}
    <tfoot>
      <tr>
        <th class="col-2">{{ date_start.year }}/{{ date_start.month }}/{{ date_start.day }}~{{ date_end.year }}/{{ date_end.month }}/{{ date_end.day }}</th>
        {% for user in users %}
        <th>{{ user.username }}</th>
        {% endfor %}
      </tr>
    </tfoot>
  </table>
  <input type="submit" class="btn btn-primary w-75 mx-auto" value="更新" />
</form>
{% endblock %}

Manager/templates/Manager/index.html
{% extends 'Manager/base.html' %} {% block content %}
<form method="post" class="table-responsive d-flex flex-column mt-2">
  {% csrf_token %}
  <input type="submit" class="btn btn-primary w-75 my-3 mx-auto" value="更新" />
  <table class="table table-sm text-nowrap align-middle">
    <thead>
      <tr>
        <th>
          <a href="{% url 'Manager:date' pre_date_start.year pre_date_start.month pre_date_start.day %}"><i class="bi bi-arrow-left-short"></i></a>{{ date_start.year }}/{{ date_start.month }}/{{ date_start.day }}~{{date_end.year }}/{{ date_end.month }}/{{ date_end.day }}
        </th>
        {% for user in users %}
        <th>{{ user.username }}</th>
        {% endfor %}
      </tr>
    </thead>
    {% for date, logs in date_logs %}
    {% if forloop.counter|divisibleby:'10' %}
    <tr>
      <th>
        {{ date_start.year }}/{{ date_start.month }}/{{ date_start.day }}~{{date_end.year }}/{{ date_end.month }}/{{ date_end.day }}
      </th>
      {% for user in users %}
      <th>{{ user.username }}</th>
      {% endfor %}
    </tr>
    {% endif %}
    <tr>
      <td>{{ date.0.year }}/{{ date.0.month }}/{{ date.0.day }}({{date.1}})</td>
      {% for log in logs %}
      <td>
        {% for field in log %}
        <p class="my-1">{{ field }}</p>
        {% endfor %}
      </td>
      {% endfor %}
    </tr>
    {% endfor %}
    <td>合計</td>
    {% for count in counts %}
    <td>{{count}}</td>
    {% endfor %}
    <tfoot>
      <tr>
        <th class="col-2">{{ date_start.year }}/{{ date_start.month }}/{{ date_start.day }}~{{ date_end.year }}/{{ date_end.month }}/{{ date_end.day }}</th>
        {% for user in users %}
        <th>{{ user.username }}</th>
        {% endfor %}
      </tr>
    </tfoot>
  </table>
  <input type="submit" class="btn btn-primary w-75 mx-auto" value="更新" />
</form>
{% endblock %}

Manager/templates/Manager/location_delete.html
<div class="modal fade" tabindex="-1" role="dialog" id="deleteModal-{{location.id}}">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">データの削除</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <p>削除すると元に戻すことはできません</p>
      </div>
      <div class="modal-footer">
        <form method="POST" action="{% url 'Manager:location_delete' location.id %}">{% csrf_token %}
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
          <button type="submit" class="btn btn-danger">削除</button>
        </form>
      </div>
    </div>
  </div>
</div>

Manager/templates/Manager/locations_manage.html
{% extends 'Manager/base.html' %} {% block content %}
<form class="d-flex px-2 mt-2" method="post">
  {% csrf_token %}
  <table class="table mx-auto">
    <tbody>
      {% for location in locations %}
      <tr>
        <td>{{location.location_name}}</td>
        <td>
          {% if location.deletibility %}
          <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal-{{location.id}}">削除</button>
          {% include "Manager/location_delete.html" with location=location %}
          {% endif %}
        </td>
      </tr>
      {% endfor %}
      <tr>
        <td>{{form.location_name}}</td>
        <td><input type="submit" class="btn btn-primary" value="追加" /></td>
      </tr>
    </tbody>
  </table>
</form>
{% endblock %}

Manager/templates/Manager/signup.html
{% extends 'User/base.html' %}

{% block content %}
<form class="mt-2 mx-auto d-flex flex-column" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-primary mx-auto" value="登録">
</form>
{% endblock content %}

Manager/templates/Manager/user_delete.html
{% extends 'Manager/base.html' %} {% block content %}
<div class="d-flex flex-column align-items-center mx-auto mt-2">
  <form class="d-flex flex-column align-items-center" method="post">
    {% csrf_token %} 
    {{form.as_p}}
    <button type="button" class="btn btn-danger btn-sm mr-1" data-bs-toggle="modal" data-bs-target="#deleteModal">削除</button>
    <div class="modal fade" tabindex="-1" role="dialog" id="deleteModal">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">ユーザー削除</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            <p>削除すると元に戻すことはできません</p>
          </div>
          <div class="modal-footer">
            <form method="POST">
              {% csrf_token %}
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">キャンセル</button>
              <button type="submit" class="btn btn-danger">削除</button>
            </form>
          </div>
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock content %}