AbeTime/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("Manager/", include("Manager.urls")),
    path("", include("User.urls")),
    path('sw.js', (TemplateView.as_view(template_name="User/sw.js",
    content_type='application/javascript', )), name='sw.js'),
]

User/urls.py
from django.urls import path
from User import views

app_name = 'User'
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("date/<int:year>/<int:month>/<int:day>", views.DateView.as_view(), name="date"),
    path("dateselect", views.DateSelectView.as_view(), name="date-select"),
    path("login/", views.AbeLoginView.as_view(), name="login"),
    path("logout/", views.AbeLogoutView.as_view(), name="logout")
]

User/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone


class AbeUser(AbstractUser):
    is_guest = models.BooleanField(default=False)


class Log(models.Model):
    date = models.DateField()
    state = models.IntegerField(default=0)
    location = models.CharField(max_length=300, null=True, blank=True)
    user = models.ForeignKey(AbeUser, on_delete=models.CASCADE)
    well_known_location = models.IntegerField(default=0)


    class Meta:
        constraints = [
            models.UniqueConstraint(fields=["user", "date"], name="log_unique"),
        ]

User/forms.py
from django import forms
from .models import Log, AbeUser
from Manager.models import WellKnownLocation
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
    UsernameField,
)
from django.utils import timezone

state_choices = [("0", "◯"), ("1", "△"), ("2", "✕")]

class LogForm(forms.Form):
    state = forms.ChoiceField(widget=forms.widgets.RadioSelect, choices=state_choices)
    well_known_location = forms.ChoiceField(widget=forms.widgets.Select(attrs={"class": "form-control"}),label="現場名")
    location = forms.CharField(required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        self.fields['well_known_location'].choices = [(location.id, location.location_name) for location in WellKnownLocation.objects.all().order_by('deletibility')]


class DateSelectForm(forms.Form):
    year = forms.ChoiceField(widget=forms.widgets.Select(attrs={"class": "form-control"}))
    month = forms.ChoiceField(widget=forms.widgets.Select(attrs={"class": "form-control"}))
    day = forms.ChoiceField(widget=forms.widgets.Select(attrs={"class": "form-control"}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['year'].choices = [
            (y, str(y) + "年")
            for y in range(timezone.now().year - 5, timezone.now().year + 1)
        ]
        self.fields['year'].initial = timezone.now().year

        self.fields['month'].choices = [(m, str(m) + "月") for m in range(1, 13)]
        self.fields['month'].initial = timezone.now().month

        self.fields['day'].choices = [(d, str(d) + "日") for d in range(1, 32)]
        self.fields['day'].initial = timezone.now().day


class LoginForm(AuthenticationForm):
    username = UsernameField(
        widget=forms.TextInput(attrs={"autofocus": True, "class": "form-control"}),
        label="ユーザー名",
    )
    password = forms.CharField(
        label=("パスワード"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "current-password", "class": "form-control"}
        ),
    )

    error_messages = {
        "invalid_login": ("ユーザー名、またはパスワードが間違っています"),
        "inactive": ("このアカウントは使用できません"),
    }

User/views.py
from typing import Any, Dict
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import (
    FormView,
    ListView,
    DeleteView,
    UpdateView,
    CreateView,
    TemplateView,
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login
from django.utils import timezone

from .forms import LoginForm, LogForm, DateSelectForm
from .models import AbeUser, Log
from datetime import date, datetime, timedelta

# Create your views here.


class IndexView(LoginRequiredMixin, FormView):
    template_name = "User/index.html"
    form_class = LogForm
    success_url = reverse_lazy("User:index")

    def get(self, request, *args, **kwargs):
        if self.request.user.is_staff:
            return redirect(reverse_lazy("Manager:index"))

        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        state = form.cleaned_data["state"]
        well_known_location = form.cleaned_data["well_known_location"]
        location = form.cleaned_data["location"]

        Log.objects.update_or_create(
            user=self.request.user,
            date=timezone.now().date(),
            defaults={"state": state, "well_known_location": well_known_location, "location": location},
        )
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        today = date.today()
        ctx["today"] = f"{today.year}/{today.month}/{today.day}"
        ctx["previous_date"] = today - timedelta(days=1)

        ctx["log"] = Log.objects.filter(
            user=self.request.user, date=timezone.now().date()
        ).first()

        return ctx


class DateView(LoginRequiredMixin, FormView):
    template_name = "User/date.html"
    form_class = LogForm

    def form_valid(self, form):
        self.success_url = reverse_lazy(
            "User:date",
            kwargs={
                "year": self.kwargs.get("year"),
                "month": self.kwargs.get("month"),
                "day": self.kwargs.get("day"),
            },
        )

        state = form.cleaned_data["state"]
        well_known_location = form.cleaned_data["well_known_location"]
        location = form.cleaned_data["location"]
        this_date = datetime.strptime(
            str(self.kwargs.get("year"))
            + "-"
            + str(self.kwargs.get("month"))
            + "-"
            + str(self.kwargs.get("day")),
            "%Y-%m-%d",
        ).date()

        Log.objects.update_or_create(
            user=self.request.user,
            date=this_date,
            defaults={"state": state, "well_known_location": well_known_location, "location": location},
        )

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)

        this_date = datetime.strptime(
            str(self.kwargs.get("year"))
            + "-"
            + str(self.kwargs.get("month"))
            + "-"
            + str(self.kwargs.get("day")),
            "%Y-%m-%d",
        )
        ctx["is_safe_date"] = this_date.date() < date.today()
        ctx["this_date"] = f"{this_date.year}/{this_date.month}/{this_date.day}"
        ctx["next_date"] = this_date + timedelta(days=1)
        ctx["previous_date"] = this_date - timedelta(days=1)

        ctx["log"] = Log.objects.filter(user=self.request.user, date=this_date).first()

        return ctx


class DateSelectView(FormView):
    template_name = "User/date_select.html"
    form_class = DateSelectForm

    def form_valid(self, form):
        year = form.cleaned_data["year"]
        month = form.cleaned_data["month"]
        day = form.cleaned_data["day"]

        self.success_url = reverse_lazy(
            "User:date", kwargs={"year": year, "month": month, "day": day}
        )

        return super().form_valid(form)


class AbeLoginView(LoginView):
    template_name = "User/login.html"
    success_url = reverse_lazy("User:index")
    form_class = LoginForm


class AbeLogoutView(LoginRequiredMixin, LogoutView):
    pass

User/templates/User/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" />
    <!-- PWA -->
    <link rel="manifest" href="{% static "manifest.json" %}" />
    <script>
      if ("serviceWorker" in navigator) {
        navigator.serviceWorker.register("{% url 'sw.js' %}").then(function () {
          console.log("Service Worker Registered");
        });
      }
    </script>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
  </head>

  <body class="d-flex flex-column">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'User:index' %}">安部板金</a>
        <a class="navbar-text" href="{% url 'User:logout' %}">ログアウト</a>
      </div>
    </nav>
    {% block content %} {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <audio id="submit_se">
      <source src="{% static "submit_se.mp3" %}" type="audio/mp3">
    </audio>
  </body>
</html>

User/templates/User/date.html
{% extends "User/base.html" %}

{% block content %}
  <div class="d-flex flex-column align-items-center mx-auto mt-2">
    {% if log != None %}
    <h6>この日はすでに記録されています</h6>
    {% endif %}
    <p>
        <a href="{% url 'User:date' previous_date.year previous_date.month previous_date.day %}"><i class="bi bi-arrow-left-short mx-3"></i></a>
        {{ this_date }}
        {% if is_safe_date %}
        <a href="{% url 'User:date' next_date.year next_date.month next_date.day %}"><i class="bi bi-arrow-right-short mx-3"></i></a>
        {% endif %}
      </p>
    <form class="d-flex flex-column align-items-center" id="log_form" method="post">
      {% csrf_token %}
      <p>
        <input type="radio" id="state1" class="btn-check" name="state" value="0">
        <label class="btn btn-outline-primary" for="state1">◯</label>
        <input type="radio" id="state2" class="btn-check" name="state" value="1">
        <label class="btn btn-outline-primary" for="state2">△</label>
        <input type="radio" id="state3" class="btn-check" name="state" value="2">
        <label class="btn btn-outline-primary" for="state3">✕</label>
      </p>
      <p>
        <label for="id_well_known_location">{{form.well_known_location.label}}:</label>
        {{form.well_known_location}}
      </p>
      <p>
        <label for="id_location">現場名:</label>
        <input type="text" name="location" class="form-control" maxlength="300" id="id_location">
      </p>
      <input type="submit" class="btn btn-primary" value="送信" onclick="se_play()">
    </form>
    <a type="button" class="btn btn-secondary mt-5" href="{% url 'User:date-select' %}">別日の入力を確認</a>
  </div>
  <script>
    function se_play(){
      event.preventDefault(); // デフォルトのページ遷移を防ぐ
  
      var se = document.getElementById("submit_se");
      se.currentTime = 0;
      se.play();

      se.onended = function() {
        document.getElementById("log_form").submit();
      };
    }
  </script>
  {% if log != None %}
  <script>
    const state_selector = document.getElementsByName('state')[{{log.state | safe}}];
    state_selector.checked = true;

    const well_known_location_selector = document.getElementsByName('well_known_location')[0];
    well_known_location_selector.value = '{{log.well_known_location | safe}}'

    const location_input = document.getElementsByName('location')[0]
    location_input.value = '{{log.location | safe}}'
  </script>
  {% endif %}
{% endblock content %}

User/templates/User/date_select.html
{% extends "User/base.html" %}

{% block content %}
<div class="d-flex flex-column align-items-center mx-auto mt-2">
    <form class="d-flex flex-column align-items-center" method="post">
        {% csrf_token %} 
        <p>
            {{form.year}}
            {{form.month}}
            {{form.day}}
        </p>
        <input type="submit" class="btn btn-primary" value="この日付の入力を確認">
    </form>
</div>
{% endblock content %}

User/templates/User/index.html
{% extends "User/base.html" %} {% block content %}
<div class="d-flex flex-column align-items-center mx-auto mt-2">
  {% if log != None %}
  <h6>今日はすでに記録されています</h6>
  {% endif %}
  <p>
    <a href="{% url 'User:date' previous_date.year previous_date.month previous_date.day %}"><i class="bi bi-arrow-left-short mx-3"></i></a>
    {{ today }}
  </p>
  <form class="d-flex flex-column align-items-center" id="log_form" method="post">
    {% csrf_token %}
    <p>
      <input type="radio" id="state1" class="btn-check" name="state" value="0" checked />
      <label class="btn btn-outline-primary" for="state1">◯</label>
      <input type="radio" id="state2" class="btn-check" name="state" value="1" />
      <label class="btn btn-outline-primary" for="state2">△</label>
      <input type="radio" id="state3" class="btn-check" name="state" value="2" />
      <label class="btn btn-outline-primary" for="state3">✕</label>
    </p>
    <p>
      <label for="id_well_known_location">{{form.well_known_location.label}}:</label>
      {{form.well_known_location}}
    </p>
    <p>
      <label for="id_location">現場詳細:</label>
      <input type="text" name="location" class="form-control" maxlength="300" id="id_location" />
    </p>
    <input type="submit" class="btn btn-primary" value="送信" onclick="se_play()"/>
  </form>
  <a type="button" class="btn btn-secondary mt-5" href="{% url 'User:date-select' %}">別日の入力を確認</a>
</div>
<script>
  function se_play(){
    event.preventDefault(); // デフォルトのページ遷移を防ぐ

    var se = document.getElementById("submit_se");
    se.currentTime = 0;
    se.play();

    se.onended = function() {
      document.getElementById("log_form").submit();
    };
  }
</script>
{% if log %}
<script>
  const state_selector = document.getElementsByName('state')[{{log.state | safe}}];
  state_selector.checked = true;

  const well_known_location_selector = document.getElementsByName('well_known_location')[0];
  well_known_location_selector.value = '{{log.well_known_location | safe}}'

  const location_input = document.getElementsByName('location')[0]
  location_input.value = '{{log.location | safe}}'
</script>
{% endif %}
{% endblock content %}

User/templates/User/login.html
{% extends 'User/base.html' %}

{% block content %}
<form class="mt-2 mx-auto d-flex flex-column" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-primary mx-auto" value="ログイン">
</form>
{% endblock content %}